#+title: Welcome
#+startup: fold latexpreview inlineimages

* Welcome to my corner!
On the Internet I am generally known as Grasshopper, or «Gafanhoto»
(Portuguese). I have been roaming around the [[https://en.wikipedia.org/wiki/Iberian_Peninsula][Iberian Peninsula]], mainly
between Lisbon, Salamanca, Barcelona and sometimes the north of
Portugal. I am currently working on the [[https://llvm.org/][LLVM Compiler Infrastructure]] in
the compiler's team of the [[https://www.bsc.es/pinto-cardoso-rafael-afonso][Barcelona Supercomputing Center]], working 
under the supervision of the spectacular [[https://rofi.roger-ferrer.org/][Roger Ibáñez]]. Previously I was 
interning under the amazing [[https://nikivazou.github.io/][Niki Vazou]] on [[https://software.imdea.org/people/alumni/][IMDEA Software]], working on
[[https://github.com/ucsd-progsys/liquidhaskell][Liquid Haskell]]. My heart is set on compilers, programming languages and 
obviously music! In case you want to contact me you have my
[[./contact.html][contact page]], or you can find me on discord on [[https://discord.gg/t6YPXq3t][DevPT]].

#+caption: [[https://en.wikipedia.org/wiki/Butterfly][A Butterfly]]
#+attr_html: :width 150px
[[./images/butterfly.svg]]

** /now
According to the [[https://ghostze.ro/now/][now page]] of [[https://ghostze.ro/about/][ghostze]] the «now» movement has been
started by [[https://sive.rs/nowff][Derek Sivers]]. It is quite a simple concept, a page where one
writes what is doing now. I will try to update it as frequently as I
can. With this, I decided to separate my «now» page from my «home» one
in order to compartmentalize things and to follow the trend properly.
My now page is: [[./now.html][now]]
